name = "gad-oracle"
main = "worker.js"
compatibility_date = "2026-03-19"

[[r2_buckets]]
binding = "ORACLE_BUCKET"
bucket_name = "gad-oracle-determinations"

[env.production]
routes = [
  { pattern = "oracle.parametricdata.io/determination/*", zone_name = "parametricdata.io" },
  { pattern = "oracle.parametricdata.io/.well-known/*", zone_name = "parametricdata.io" }
]
