[theme]
base = "light"
primaryColor = "#0969da"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f6f8fa"
textColor = "#1f2328"
font = "sans serif"

[server]
maxUploadSize = 5

[browser]
gatherUsageStats = false
